project_name = "Coiner"
project_version = "2.12.11"

[app]
host_visible = false
llm_provider = "deepseek"
stop_on_api_failure = true
pollinations_base_url = "https://pollinations.ai/api/v1"
pollinations_model_name = "openai-fast"
ollama_base_url = "http://host.docker.internal:11434/v1"
ollama_model_name = "qwen:7b"
openai_base_url = ""
openai_model_name = "gpt-4o-mini"
moonshot_base_url = "https://api.moonshot.cn/v1"
moonshot_model_name = "moonshot-v1-8k"
oneapi_base_url = ""
oneapi_model_name = ""
g4f_model_name = "gpt-3.5-turbo"
azure_base_url = ""
azure_model_name = "gpt-35-turbo"
azure_api_version = "2024-02-15-preview"
gemini_model_name = "gemini-1.0-pro"
qwen_model_name = "qwen-max"
deepseek_base_url = "https://api.deepseek.com"
deepseek_model_name = "deepseek-chat"
modelscope_base_url = "https://api-inference.modelscope.cn/v1/"
modelscope_model_name = "Qwen/Qwen3-32B"
subtitle_provider = "edge"
endpoint = ""
enable_redis = false
redis_host = "localhost"
redis_port = 6379
redis_db = 0
max_concurrent_tasks = 1
console_log_level = "INFO"

[video]
video_source = "pexels"
use_gpu = true
video_quality = "ultra"
video_bitrate = "20M"
video_brightness = 1.15
video_contrast = 1.05
video_concat_mode = "random"
video_transition_mode = "none"
min_scene_success_ratio = 0.9
video_aspect = "landscape_4_3"
video_clip_duration = 4
video_count = 1
silence_duration = 1
video_style = "none"
intro_video_bg_type = "blurred"
intro_video_bg_blur = 48
intro_video_bg_color = "black"
intro_image_animation_enabled = true
intro_image_zoom_amount = 0.03
material_directory = ""
max_parallel_scenes = 2
output_bg_color = "black"

[whisper]
model_size = "large-v3"
device = "GPU"
compute_type = "int8"

[proxy]

[azure]
speech_region = ""

[siliconflow]

[audio]
tts_server = "coze-tts"
voice_name = "coze|7524987545197805587|爽快思思（多情感）-Female|https://lf3-appstore-sign.oceancloudapi.com/ocean-cloud-tos/VolcanoSystemVoice/zh_female_shuangkuaisisi_emo_v2_mars_bigtts.mp3?lk3s=da27ec82&x-expires=1784908851&x-signature=jHd7K2qGx70iW%2BP6XSAumZOVuIo%3D|今天天气可好了，我打算和朋友一起去野餐，带上美食和饮料，找个舒适的草坪，什么烦恼都没了。你要不要和我们一起呀？|angry-生气,coldness-冷漠,excited-激动,happy-开心,neutral-中性,sad-悲伤,surprised-惊讶"
voice_volume = 1.8
voice_rate = 1.1
bgm_type = ""
bgm_volume = 0.1

[subtitle]
subtitle_enabled = true
subtitle_position = "custom"
subtitle_custom_position = 95
subtitle_margin = 0.05
subtitle_auto_fit = false
font_name = "MicrosoftYaHeiBold.ttc"
text_fore_color = "rgb(246, 246, 244)"
text_background_color = true
font_size = 54
stroke_color = "rgb(241, 246, 106)"
stroke_width = 1.2

[title]
title_enabled = true
title_text = "644分错进分校\n一年白读"
title_duration = 1
title_font_name = "MicrosoftYaHeiBold.ttc"
title_font_size = 100
title_text_color = "#FFFFFF"
title_stroke_color = "#A52A2A"
title_stroke_width = 5
title_background_color = "transparent"
title_position = "center"
title_margin = 0.06
title_margin_left = 0.02
title_margin_right = 0.02
title_animation = "none"
title_animation_duration = 0.5
title_background_overlay = true
title_overlay_color = "rgba(0,0,0,0.5)"
title_style = "classic"
title_align = "center"

[ui]
hide_log = false
language = "zh"

[coze]

[qwen]

[tavily]

[storage]
storage_cleanup_interval_hours = 1
local_videos_ttl_days = 3
cache_videos_ttl_days = 7
cache_downscaled_ttl_days = 7
temp_ttl_hours = 1

[imagemagick]
imagemagick_path = "D:\\ProgramData\\ImageMagick-7.1.12-Q16\\magick.exe"
